version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AKIAYYWULDALJ46FAS4E
          aws-cli-version: latest
          aws-secret-access-key: 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
          dockerfile: Dockerfile
          executor: aws-ecr/default
          region: us-west-2
          registry-id: 602814486550
          repo: circleci-aws

